-- Remove Hibernate-generated CHECK constraint for car.model
-- This constraint is auto-generated by Hibernate with hardcoded enum values,
-- which breaks when new car models are added to the CarBrand.CarModel enum.
-- JPA validation is sufficient on the application level.

-- Drop the CHECK constraint if it exists
ALTER TABLE car DROP CONSTRAINT IF EXISTS car_model_check;

-- Note: JPA @Enumerated(EnumType.STRING) still validates the model field
-- on the application level, so we don't need a DB-level CHECK constraint.
