package com.evmonitor.infrastructure.web;

import com.evmonitor.infrastructure.github.GitHubIssueService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
@RequestMapping("/api/errors")
public class FrontendErrorController {

    private final GitHubIssueService gitHubIssueService;

    public FrontendErrorController(GitHubIssueService gitHubIssueService) {
        this.gitHubIssueService = gitHubIssueService;
    }

    @PostMapping("/frontend")
    public ResponseEntity<Void> reportError(@RequestBody @Valid FrontendErrorRequest request) {
        // Rate-limit key: first 80 chars of the error message
        String errorKey = "fe_" + request.message().substring(0, Math.min(80, request.message().length()));
        String subject = "🌐 [EV Monitor FE] " + request.message().substring(0, Math.min(100, request.message().length()));
        gitHubIssueService.createIssue(errorKey, subject, buildGitHubIssueBody(request));
        return ResponseEntity.ok().build();
    }

    private String buildGitHubIssueBody(FrontendErrorRequest request) {
        return """
                ## Frontend Error

                | Field | Value |
                |-------|-------|
                | **Time** | `%s` |
                | **URL** | `%s` |
                | **Info** | `%s` |
                | **Message** | `%s` |

                ## Stack

                ```
                %s
                ```

                ---
                *Auto-generated by EV Monitor error handler. Label `auto-fix` triggers automated analysis.*
                """.formatted(
                java.time.Instant.now(),
                request.url() != null ? request.url() : "unknown",
                request.info() != null ? request.info() : "unknown",
                request.message(),
                request.stack() != null ? request.stack() : "(no stack)"
        );
    }


}
