package com.evmonitor.infrastructure.web;

import com.evmonitor.infrastructure.github.GitHubIssueService;
import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.servlet.resource.NoResourceFoundException;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.time.Instant;
import java.util.Map;

@RestControllerAdvice
public class GlobalExceptionHandler {

    private static final Logger log = LoggerFactory.getLogger(GlobalExceptionHandler.class);

    private final GitHubIssueService gitHubIssueService;

    public GlobalExceptionHandler(GitHubIssueService gitHubIssueService) {
        this.gitHubIssueService = gitHubIssueService;
    }

    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<Map<String, String>> handleIllegalArgument(IllegalArgumentException ex) {
        String code = ex.getMessage();
        HttpStatus status = switch (code) {
            case "TOKEN_EXPIRED" -> HttpStatus.GONE;
            case "INVALID_TOKEN" -> HttpStatus.BAD_REQUEST;
            case "EMAIL_NOT_VERIFIED" -> HttpStatus.FORBIDDEN;
            case "RATE_LIMITED" -> HttpStatus.TOO_MANY_REQUESTS;
            default -> HttpStatus.BAD_REQUEST;
        };
        return ResponseEntity.status(status).body(Map.of("code", code, "message", friendlyMessage(code)));
    }

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Map<String, String>> handleValidation(MethodArgumentNotValidException ex) {
        String message = ex.getBindingResult().getAllErrors().stream()
                .findFirst()
                .map(e -> e.getDefaultMessage())
                .orElse("Ungültige Eingabe.");
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(Map.of("code", "VALIDATION_ERROR", "message", message));
    }

    @ExceptionHandler(BadCredentialsException.class)
    public ResponseEntity<Map<String, String>> handleBadCredentials(BadCredentialsException ex) {
        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("code", "INVALID_CREDENTIALS", "message", "Ungültige Anmeldedaten."));
    }

    @ExceptionHandler(AccessDeniedException.class)
    public ResponseEntity<Map<String, String>> handleAccessDenied(AccessDeniedException ex) {
        return ResponseEntity.status(403).body(Map.of("code", "FORBIDDEN", "message", "Zugriff verweigert."));
    }

    // Spring MVC 4xx – kein Alert, kein Log-Spam
    @ExceptionHandler(NoResourceFoundException.class)
    public ResponseEntity<Map<String, String>> handleNoResource(NoResourceFoundException ex) {
        return ResponseEntity.status(404).body(Map.of("code", "NOT_FOUND", "message", "Resource not found."));
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<Map<String, String>> handleUnexpected(Exception ex, HttpServletRequest request) {
        log.error("Unhandled exception on {} {}", request.getMethod(), request.getRequestURI(), ex);

        String errorKey = ex.getClass().getName();
        String subject = "🚨 [EV Monitor BE] " + ex.getClass().getSimpleName();
        gitHubIssueService.createIssue(errorKey, subject, buildGitHubIssueBody(ex, request));

        return ResponseEntity.status(500).body(Map.of(
                "code", "INTERNAL_ERROR",
                "message", "Ein interner Fehler ist aufgetreten."
        ));
    }

    private String buildGitHubIssueBody(Exception ex, HttpServletRequest request) {
        StringWriter sw = new StringWriter();
        ex.printStackTrace(new PrintWriter(sw));
        String stackTrace = sw.toString();
        if (stackTrace.length() > 5000) {
            stackTrace = stackTrace.substring(0, 5000) + "\n... (truncated)";
        }

        return """
                ## Backend Error

                | Field | Value |
                |-------|-------|
                | **Time** | `%s` |
                | **Request** | `%s %s` |
                | **Exception** | `%s` |
                | **Message** | `%s` |

                ## Stacktrace

                ```
                %s
                ```

                ---
                *Auto-generated by EV Monitor error handler. Label `auto-fix` triggers automated analysis.*
                """.formatted(
                Instant.now(),
                request.getMethod(),
                request.getRequestURI(),
                ex.getClass().getName(),
                ex.getMessage(),
                stackTrace
        );
    }

    private String friendlyMessage(String code) {
        return switch (code) {
            case "TOKEN_EXPIRED" -> "Der Bestätigungs-Link ist abgelaufen. Bitte fordere einen neuen an.";
            case "INVALID_TOKEN" -> "Ungültiger Bestätigungs-Link.";
            case "EMAIL_NOT_VERIFIED" -> "Bitte bestätige zuerst deine E-Mail-Adresse.";
            case "RATE_LIMITED" -> "Bitte warte kurz, bevor du erneut eine E-Mail anforderst.";
            case "Email is already in use." -> "Diese E-Mail-Adresse ist bereits registriert.";
            case "Username is already taken." -> "Dieser Username ist bereits vergeben.";
            default -> code;
        };
    }
}
